<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://api.shutterstock.com/v2/test");
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HTTPHEADER, array( 'Content-Type: application/json'));


$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}

  $info = curl_getinfo($ch);  
  echo 'content type: ' . $info['content_type'] . '<br />';
  echo 'http code: ' . $info['http_code'] . '<br />';


curl_close ($ch);


echo $result;

/*
$ curl --get --user ${37d63-38581-5676e-891c3-f21e6-c2499}:${275b4-71710-00e6c-93db5-40b34-19328} \
 https://api.shutterstock.com/v2/images/search \
 --data-urlencode "query=donkey"
 */